const Api=[{"fname":"pooja",
"lname":"poddar",
"cateogory":"3",
"age":78,
"education":"bcom"},
{"fname":"ladli",
"cateogory":"2",
"lname":"jha",
"age":48,
"education":"mcom"},
{"fname":"shivani",
"cateogory":"1",
"lname":"chaudhri",
"age":38,
"education":"bsc"},
{"fname":"sakshi",
"cateogory":"1",
"lname":"roy",
"age":18,
"education":"ba"},
{"fname":"riya",
"lname":"rani",
"cateogory":"1",
"age":28,
"education":"bao"},
]

export default Api;